package model;
// Generated 06-oct-2020 18:18:44 by Hibernate Tools 4.3.1

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 * Person generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Person implements Serializable {

    private Long id;
    private String name;
    private String telephone;
    private String address;

    public Person() {
    }

	
    public Person(Long id) {
        this.id = id;
    }
    public Person(Long id, String name, String telephone, String address) {
       this.id = id;
       this.name = name;
       this.telephone = telephone;
       this.address = address;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
}